server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_db?useSSL=false&serverTimezone=UTC
    username: root
    password: nandini
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    initialize-schema: true
