server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment_db?useSSL=false&serverTimezone=UTC
    username: root
    password: nandini
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    initialize-schema: true

feign:
  hystrix:
    enabled: true